TournamentStart: "&bThe tournament will start in %time% seconds"
Prefix: "&6&lPVP-ROUNDS &f"
TournamentTimeChanged: "&eThe tournament time changed!"
TournamentStarted: "&bThe tournament started"
PlayerJoinedMatch: "&e%player% joined the event!"
PlayerLeaveServer: "&e%player% left the server while in the event and lost"
PlayerLeaveServerDeath: "&c%player% left the server while in the event and lost"
PlayerKilledMessage: "&cYou got killed and lost the PvP Tournament"
PlayerKilledBroadcast: "&b%player% died to %killer% in the PvP Tournament!"
PlayersLeft: "&b%left% Players Left"
Searching: "&bSearching for the next two Players for Battle!"
CommandBlockedInBattle: "&eThis command is blocked while in PvP Tournament!"
CommandBlocked: "&eWrite /pvprounds leave to leave the event"
EventWinner: "&a%player% wins the event PvP Tournament!"
Fight: "&6NEXT FIGHT: &e%player1% VS %player2%"
FightAgainst: "&aYou will fight against %player%"
SwordName: "&aSword"
Joined: "&eYou joined the tournament"
JoinTitle: "&eYou joined"
JoinSubTitle: "&fThe tournament"
TournamentLeave: "You leave the tournament!"
TournamentStartGlobal: "&eA PvP tournament will start on %time% seconds. Click here to join"
ClickToJoin: "&bClick here to join!"
SendIPAddressData: true